### ISSUE TITLE
MacOS Java issue

### ISSUE THREAD

**Issue by altandheckeldir** [GazePlay/GazePlay#782]
Hi I can't run the script on my MacBook Pro Mojave with JRE 1.8.0_211

Any idea?

Thx!

./gazeplay-macos.sh 
WORKING_DIR = /Users/thomasbertrand/Downloads/gazeplay-dist-1.5.1/bin
SCRIPT_DIR = .
LIB_DIR = ./../lib
Executing command line: java -Xms256m -Xmx1g -jar ./../lib/gazeplay-1.5.1.jar
2019-06-15 18:40:08,244 INFO  - Replaced standard System.out and System.err PrintStreams with SLF4JPrintStreams
2019-06-15 18:40:08,248 INFO  - Redirected System.out and System.err to SLF4J for this context
2019-06-15 18:40:08,251 INFO  - ***********************
2019-06-15 18:40:08,251 INFO  - ***********************
2019-06-15 18:40:08,251 INFO  - ***********************
2019-06-15 18:40:08,251 INFO  - ***********************
2019-06-15 18:40:08,251 INFO  - ***********************
2019-06-15 18:40:08,251 INFO  - GazePlay
2019-06-15 18:40:08,251 INFO  - Version : 1.5.1 (2019-04-04T16:28:16Z)
2019-06-15 18:40:08,256 ERROR - uncaughtException in Thread application-bootsrap--Thread-1 : java.lang.NoClassDefFoundError : javafx/beans/value/ObservableValue
java.lang.NoClassDefFoundError: javafx/beans/value/ObservableValue
	at net.gazeplay.GazePlayLauncher$1.run(GazePlayLauncher.java:53)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.ClassNotFoundException: javafx.beans.value.ObservableValue
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 common frames omitted

**Comment by schwabdidier** [comment]
Yes @altandheckeldir, it is an already known bug (see #601). For now, it was not an high-priority bug as we don't have easy access to eye-tracker on macOS (but we also work on that). But as you are the third to ask... I try to resolve it before next release (~ 1st of July).

**Comment by altandheckeldir** [comment]
OK many thanks! I have tried the proposed script from #601 (after changing the version number and installing realpath that is not by default on MacosX), but I got the exact same error... I guess I will wait fro the next release.

**Comment by schwabdidier** [comment]
we add a patch for macOS

**Comment by altandheckeldir** [comment]
Sorry but it is still not working on fresh 1.6.1 (MacOS X Catalina).

./gazeplay-macos.sh
Executing command line: java -Xms256m -Xmx1g -jar ../lib/gazeplay-1.6.1.jar
2019-11-11 15:00:39,533 DEBUG - Your logging framework class ch.qos.logback.classic.Logger should not need access to the standard println methods on the console, so you should not need to register a logging system package.
2019-11-11 15:00:39,549 INFO  - Replaced standard System.out and System.err PrintStreams with SLF4JPrintStreams
2019-11-11 15:00:39,555 INFO  - Redirected System.out and System.err to SLF4J for this context
2019-11-11 15:00:39,559 INFO  - ***********************
2019-11-11 15:00:39,560 INFO  - ***********************
2019-11-11 15:00:39,560 INFO  - ***********************
2019-11-11 15:00:39,560 INFO  - ***********************
2019-11-11 15:00:39,560 INFO  - ***********************
2019-11-11 15:00:39,560 INFO  - GazePlay
2019-11-11 15:00:39,560 INFO  - Version : 1.6.1 (2019-09-04T14:59:07Z)
2019-11-11 15:00:39,566 ERROR - uncaughtException in Thread application-bootsrap--Thread-1 : java.lang.NoClassDefFoundError : javafx/beans/value/ObservableValue
java.lang.NoClassDefFoundError: javafx/beans/value/ObservableValue
	at net.gazeplay.GazePlayLauncher$1.run(GazePlayLauncher.java:53)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.ClassNotFoundException: javafx.beans.value.ObservableValue
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 common frames omitted

**Comment by kuhlkrein** [comment]
@schwabdidier it seems to be a 'classpath' problem:

[](https://www.commentcamarche.net/forum/affich-50409-java-lang-noclassdeffounderror)

maybe there is something a bit special to do with classpath for macOS ?

**Comment by Tohaker** [comment]
@altandheckeldir We've made some changes to the macos scripts since you opened this Issue, Could you see if this issue still affects you with the latest `master`?

**Comment by altandheckeldir** [comment]
Hi,

I am not a developer but only an end-user. I git-clonned master and followed the instructions how to build from source. Everything seemed to be fine. However I don’t understand were he binaries are…. When I go to gazeplay-dist/src/main/bin and execute the gazeplay-macos.sh , it does not find ../lib.

Sorry for the noob answer.

**Comment by Tohaker** [comment]
No need to apologise, we were all noobs once!

You'll need to build the project first, by running `./gradlew packageApp`. Once that finishes (it can take 5-10 mins) you will find a new folder in the root of the folder called `build`. Inside there you'll find a folder called `distributions` and there will be the zip and tar files we upload to Releases on GitHub. You can extract the files and then run the shell script from the bin folder in there.

**Comment by altandheckeldir** [comment]
Hurray!!!! It worked like a charm! I have been testing a few games with my theeyetribe tracker and it works just fine!

Funny that I tried all options with gradlew except the packageApp…

Many thanks! You can close the issue.

**Comment by schwabdidier** [comment]
@altandheckeldir Thank you very much for your help :)

@all gg !
